name: bmicalculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true